name: pill_time
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.4
  provider: ^6.1.5+1
  flutter_mdi_icons: ^0.1.3
  flutter_local_notifications: ^20.1.0
  timezone: ^0.10.1
  image_picker: ^1.2.1
  flutter_foreground_task: ^9.2.1
  hive_flutter: ^1.1.0
  flutter_tts: ^4.2.5
  volume_controller: ^3.4.4
  confetti: ^0.8.0
  shared_preferences: ^2.5.5
  pdf: ^3.12.0
  printing: ^5.14.3
  screen_state: ^5.0.0
  mask_text_input_formatter: ^2.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4


flutter:
  uses-material-design: true

  assets:
    - assets/pill.svg
    - assets/star.svg
    - assets/pill.png


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/pill.png"